# Generated by Django 5.0.2 on 2024-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
