# Generated by Django 5.0.2 on 2024-02-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Мое описание', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
