# Generated by Django 5.0.2 on 2024-03-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
