# Generated by Django 5.0.2 on 2024-03-01 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_last_send',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего уведомления'),
        ),
    ]
