# Generated by Django 4.2.10 on 2024-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_course_time_last_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
